#!/bin/sh

VERSION=`ls target/*.jar |sed -e 's/\.jar//g'| sed -e 's/spring-petclinic-//g' |xargs basename`

docker tag spring-petclinic:$VERSION iamfuzz.jfrog.io/docker/spring-petclinic:$VERSION
docker push iamfuzz.jfrog.io/docker/spring-petclinic:$VERSION
