#!/bin/sh

VERSION=`ls target/*.jar |sed -e 's/\.jar//g'| sed -e 's/spring-petclinic-//g' |xargs basename`

sudo docker tag spring-petclinic:$VERSION iamfuzz.jfrog.io/docker/spring-petclinic:$VERSION
sudo docker push iamfuzz.jfrog.io/docker/spring-petclinic:$VERSION
